---
- name: Deployment
  delegate_to: localhost
  run_once: true
  block:
    - name: Add longhorn repository
      kubernetes.core.helm_repository:
        repo_name: longhorn
        repo_url: https://charts.longhorn.io

    - name: Install longhorn
      kubernetes.core.helm:
        state: present
        update_repo_cache: true
        name: longhorn
        release_namespace: longhorn-system
        create_namespace: true
        chart_ref: longhorn/longhorn
        chart_version: 1.3.2
        release_values:
          longhornManager:
            tolerations:
              - key: queue-worker
                effect: NoSchedule
                operator: Exists
          longhornDriver:
            tolerations:
              - key: queue-worker
                effect: NoSchedule
                operator: Exists