---
- name: Remove dodgy repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/repository_egi_eu_sw_production_cas_1_current.list
    state: absent

- name: Update cache
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: ugrade all packages on Ubuntu
  become: true
  ansible.builtin.apt:
    upgrade: yes

- name: Download and import Redpanda GPG Key without proxy
  become: true
  args:
    creates: /usr/share/keyrings/redpanda-redpanda-archive-keyring.gpg
  ansible.builtin.shell: |
    curl -1sLf "https://dl.redpanda.com/sMIXnoa7DK12JW4A/redpanda/gpg.988A7B0A4918BC85.key" | gpg --dearmor > /usr/share/keyrings/redpanda-redpanda-archive-keyring.gpg


- name: Add Redpanda DEB repository
  ansible.builtin.copy:
    dest: "/etc/apt/sources.list.d/redpanda-redpanda.list"
    content: "deb [signed-by=/usr/share/keyrings/redpanda-redpanda-archive-keyring.gpg] https://dl.redpanda.com/public/redpanda/deb/{{ansible_distribution | lower}} {{ ansible_distribution_release | lower }} main"
    owner: root
    group: root
    mode: '0644'

- name: Install redpanda
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: redpanda
    state: present

- name: Tune kernel for prod
  ansible.builtin.shell: |
    sudo rpk redpanda mode production
    sudo rpk redpanda tune all
    sudo systemctl start redpanda-tuner


- name: Bootstrap seed server configuration
  delegate_to: 130.246.81.45
  ansible.builtin.shell: |
    sudo rpk redpanda config bootstrap --self 0.0.0.0 --ips 130.246.81.45,130.246.81.166,130.246.81.188
    sudo rpk redpanda config set redpanda.empty_seed_starts_cluster true
    sudo rpk redpanda config set redpanda.auto_create_topics_enabled true
    sudo rpk redpanda config set redpanda.kafka_api '[{ "address": "0.0.0.0", "port": 9092 }]'
    sudo rpk redpanda config set redpanda.advertised_kafka_api '[{ "address": "{{ ansible_host }}", "port": 9092 }]'

- name: Copy server 3 Config
  ansible.builtin.copy:
    src: redpanda-0.yml
    dest: /etc/redpanda/redpanda.yaml
  delegate_to: 130.246.81.45

- name: Bootstrap server 2 configuration
  delegate_to: 130.246.81.166
  ansible.builtin.shell: |
    sudo rpk redpanda config bootstrap --self 0.0.0.0 --ips 130.246.81.45,130.246.81.166,130.246.81.188
    sudo rpk redpanda config set redpanda.empty_seed_starts_cluster false
    sudo rpk redpanda config set redpanda.auto_create_topics_enabled true
    sudo rpk redpanda config set redpanda.kafka_api '[{ "address": "0.0.0.0", "port": 9092 }]'
    sudo rpk redpanda config set redpanda.advertised_kafka_api '[{ "address": "{{ ansible_host }}", "port": 9092 }]'

- name: Copy server 2 config
  ansible.builtin.copy:
    src: redpanda-2.yml
    dest: /etc/redpanda/redpanda.yaml
  delegate_to: 130.246.81.166

- name: Bootstrap server 3 configuration
  delegate_to: 130.246.81.188
  ansible.builtin.shell: |
    sudo rpk redpanda config bootstrap --self 0.0.0.0 --ips 130.246.81.45,130.246.81.166,130.246.81.188
    sudo rpk redpanda config set redpanda.empty_seed_starts_cluster false
    sudo rpk redpanda config set redpanda.auto_create_topics_enabled true
    sudo rpk redpanda config set redpanda.kafka_api '[{ "address": "0.0.0.0", "port": 9092 }]'
    sudo rpk redpanda config set redpanda.advertised_kafka_api '[{ "address": "{{ ansible_host }}", "port": 9092 }]'

- name: Copy server 3 Config
  ansible.builtin.copy:
    src: redpanda-3.yml
    dest: /etc/redpanda/redpanda.yaml
  delegate_to: 130.246.81.188

- name: Restart Redpanda
  ansible.builtin.systemd:
    name: redpanda
    state: restarted
    enabled: true

#- name: Start redpanda
#  ansible.builtin.systemd_service:
#    state: started
#    name: redpanda