---
- name: Mount ceph
  become: true
  block:
    - name: Create autoreduce group
      group:
        name: autoreduce
        gid: "{{ isis_ceph.uid }}"
        state: present
      when: "'workers' in group_names or inventory_hostname == 'localhost'"

    - name: Create autoreduce user
      user:
        name: autoreduce
        shell: /bin/bash
        state: present
        uid: "{{ isis_ceph.uid }}"
        group: autoreduce
      when: "'workers' in group_names or inventory_hostname == 'localhost'"

    - name: Ensure dependencies are installed
      apt:
        update_cache: true
        name: ceph
        state: present
      when: "'workers' in group_names or inventory_hostname == 'localhost'"

    - name: Create directory
      ansible.builtin.file:
        path: /ceph
        state: directory
        mode: "u=rwx,g=rx,o=rx"
      when: "'workers' in group_names or inventory_hostname == 'localhost'"

    - name: Ensure ceph secret key is present
      ansible.builtin.copy:
        dest: /etc/ceph/deneb.key
        content: "{{ isis_ceph.key }}"
        owner: root
        group: root
        mode: "u=r,g=,o="
      when: "'workers' in group_names or inventory_hostname == 'localhost'"

    - name: Mount CEPH
      ansible.builtin.mount:
        path: /ceph
        src: deneb-mon1.nubes.rl.ac.uk,deneb-mon2.nubes.rl.ac.uk,deneb-mon3.nubes.rl.ac.uk:/isis/instrument
        fstype: ceph
        opts: "name=isis_autoreduce,secretfile=/etc/ceph/deneb.key,noatime,_netdev"
        state: mounted
      retries: 100
      delay: 1
      register: result
      until: result.failed == false
      when: "'workers' in group_names or inventory_hostname == 'localhost'"