---
- name: Deployment of ir-api
  delegate_to: localhost
  run_once: true
  block:
    - name: Create ir namespace if it doesn't exist
      kubernetes.core.k8s:
        state: present
        name: ir
        api_version: v1
        kind: Namespace

    - name: Install ir-api
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'ir-api.yml.j2') }}"