---
- name: Create fake ceph
  become: true
  block:
    - name: Ensure ceph is not a mounted volume
      ansible.builtin.mount:
        path: /ceph
        state: absent
      when: "'workers' in group_names or inventory_hostname == 'localhost'"

    - name: Delete ceph folder before re-creation
      ansible.builtin.file:
        state: absent
        path: /ceph
      when: "'workers' in group_names or inventory_hostname == 'localhost'"

    - name: Create instrument directories in ceph
      ansible.builtin.file:
        path: "/ceph/{{ item }}/RBNumber/unknown/autoreduced"
        state: directory
        mode: "u=rwx,g=rx,o=rx"
      loop:
        - ALF
        - ARGUS
        - CHRONUS
        - Calibration
        - CRISP
        - EMU
        - ENGINX
        - Focus
        - GEM
        - HIFI
        - HRPD
        - IMAT
        - INES
        - INTER
        - IRIS
        - LARMOR
        - LET
        - LOQ
        - MAPS
        - MARI
        - MERLIN
        - MUSR
        - NIMROD
        - OFFSPEC
        - OSIRIS
        - POLARIS
        - POLREF
        - SANDALS
        - SANS2D
        - SURF
        - SXD
        - TOSCA
        - TRAINING
        - VESUVIO
        - WISH
        - ZOOM
      when: "'workers' in group_names or inventory_hostname == 'localhost'"