---
- name: Taint the queue worker nodes
  delegate_to: localhost
  run_once: true
  block:
    - name: Find all nodes
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Node
        namespace: default
      register: nodes
    
    - name: Filter nodes for just the queue nodes
      set_fact:
        queue_nodes: "{{ nodes.resources | json_query('[?contains(metadata.name, `queue`)]') }}"

    - name: Taint the queue worker nodes
      kubernetes.core.k8s_taint:
        state: present
        name: "{{ item.metadata.name }}"
        taints:
        - effect: NoSchedule
          key: queue-worker
      loop: "{{ queue_nodes }}"