---
- name: Deployment
  delegate_to: localhost
  run_once: true
  block:
    - name: Add Promtail (Grafana) repository
      kubernetes.core.helm_repository:
        repo_name: grafana
        repo_url: https://grafana.github.io/helm-charts

    - name: Ensure Promtail is deployed
      kubernetes.core.helm:
        update_repo_cache: false
        name: promtail
        namespace: promtail
        create_namespace: true
        chart_ref: grafana/promtail
        chart_version: 6.6.0
        release_values:
          config:
            clients:
              - url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
                basic_auth:
                  username: "{{ grafana_cloud_promtail.username }}"
                  password: "{{ grafana_cloud_promtail.token }}"
          tolerations: [
            {
              "effect": "NoSchedule",
              "key": "node-role.kubernetes.io/master",
              "operator": "Exists"
            },
            {
              "effect": "NoSchedule",
              "key": "node-role.kubernetes.io/control-plane",
              "operator": "Exists"
            },
            {
              "effect": "NoSchedule",
              "key": "queue-worker",
              "operator": "Exists"
            }
          ]
        state: present
