---
- name: Deployment of kafka
  delegate_to: localhost
  run_once: true
  block:
    - name: Add strimzi repository
      kubernetes.core.helm_repository:
        repo_name: strimzi
        repo_url: https://strimzi.io/charts/

    - name: Install kafka
      kubernetes.core.helm:
        update_repo_cache: false
        name: kafka
        release_namespace: kafka
        create_namespace: true
        chart_ref: strimzi/strimzi-kafka-operator
      
    - name: Create a kafka cluster
      kubernetes.core.k8s:
        state: present
        src: files/kafka-cluster.yml