---
- name: Deployment of rundetection
  delegate_to: localhost
  run_once: true
  block:
    - name: Create ir namespace if it doesn't exist
      kubernetes.core.k8s:
        state: present
        name: ir
        api_version: v1
        kind: Namespace

    - name: Install rundetection
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'rundetection.yml.j2') }}"
    
    - name: Add kafka topic for rundetection
      kubernetes.core.k8s:
        state: present
        src: kafka-topic.yml
