---
- name: Deployment of rundetection
  delegate_to: localhost
  run_once: true
  block:
    - name: Create ir namespace if it doesn't exist
      kubernetes.core.k8s:
        state: present
        name: ir
        api_version: v1
        kind: Namespace

    - name: Install rundetection
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: rundetection
            namespace: ir
          spec:
            selector:
              matchLabels:
                app: rundetection
            template:
              metadata:
                labels:
                  app: rundetection
              spec:
                containers:
                - name: rundetection
                  image: ghcr.io/interactivereduction/rundetection:2022-12-14T15-10-16
                  env:
                  - name: ACTIVEMQ_IP
                    value: 172.16.100.197
                  resources:
                    limits:
                      memory: "128Mi"
                      cpu: "500m"
                  volumeMounts:
                    - name: archive-mount
                      mountPath: /archive
              volumes:
                - name: archive-mount
                  hostPath:
                    path: /archive
