---
- name: Deployment of grafana agent operator
  delegate_to: localhost
  run_once: true
  block:
    - name: Create ir namespace if it doesn't exist
      kubernetes.core.k8s:
        state: present
        name: grafana
        api_version: v1
        kind: Namespace

    - name: Install grafana agent operator
      kubernetes.core.k8s:
        state: present
        src: grafana-agent-operator.yml

    - name: Install grafana agent resource
      kubernetes.core.k8s:
        state: present
        src: grafana-agent.yml
    
    - name: Install grafana agent metric instance
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'metrics-instance.yml.j2') }}"

    - name: Create a credentials secret in Kubernetes for metrics
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'metrics-credentials.yml.j2') }}"
    
    - name: Create a kubelet service monitor
      kubernetes.core.k8s:
        state: present
        src: kubelet-service-monitor.yml
    
    - name: Create a cAdvisor service monitor
      kubernetes.core.k8s:
        state: present
        src: cadvisor-service-monitor.yml
    
    - name: Create a LogsInstance
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'logs-instance.yml.j2') }}"

    - name: Create a credentials secret in Kubernetes for Logs
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'logs-credentials.yml.j2') }}"
    
    - name: Create a PodLogs
      kubernetes.core.k8s:
        state: present
        src: pod-logs.yml
