---
- name: Deployment
  delegate_to: localhost
  run_once: true
  block:
    - name: Add prometheus repository
      kubernetes.core.helm_repository:
        repo_name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Install prometheus
      kubernetes.core.helm:
        update_repo_cache: true
        name: prometheus
        namespace: prometheus
        create_namespace: true
        chart_ref: prometheus-community/prometheus
        chart_version: 18.0.0
        release_values: # available values: https://github.com/prometheus-community/helm-charts/blob/prometheus-17.0.0/charts/prometheus/values.yaml
          alertmanager:
            enabled: false
          prometheus-pushgateway:
            enabled: false
          prometheus-node-exporter:
            tolerations:
              - effect: NoSchedule
                operator: Exists
              - effect: NoSchedule
                key: queue-worker
                operator: Exists
          server:
            persistentVolume:
              enabled: true
              accessModes:
                - ReadWriteOnce
              storageClass: longhorn
            remoteWrite:
              - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
                basic_auth:
                  username: "{{ grafana_cloud_prometheus.username }}"
                  password: "{{ grafana_cloud_prometheus.token }}"
                write_relabel_configs:
                  - source_labels:
                      - __name__
                    regex: "{{ lookup('file', 'metrics-to-include.txt').strip().split('\n') | join('|') }}"
                    action: keep
                  - source_labels:
                      - __name__
                      - device
                    regex: "node_network.*;veth.*"
                    action: drop
        state: present
