---
- name: Deploy cluster requirements
  hosts: all
  vars_files:
    - group_vars/all/vault.yml
  roles:
    - role: firewall
    - role: cilium
    - role: traefik
    - role: longhorn
    - role: prometheus
    - role: promtail
